Wow, that's some messy code!
Almantask/CSharp-From-Zero-To-Hero pull request #399
Opened 2020-05-20 22:51 UTC by inz-

2020-05-23 13:47 UTC, Almantask requested changes
Please redo the homework by understanding how to implement each function yourself, and not using the language features yet.

2020-05-23 13:47 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            Array.Reverse(array);
Don't cheat! 😄 Please implement this by yourself. No C#-unique language features are yet allowed.

2020-05-23 13:47 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +                Array.Sort(array);
Implement this yourself 😄

2020-05-28 20:47 UTC, Almantask requested changes
A lot of methods can be reused when you removeAt or InsertAt a given index.

2020-05-28 20:47 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
RemoveLast is actually RemoveAt(last)

2020-05-28 20:47 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveFirst(int[] array)
RemoveAt(0)

2020-05-29 08:02 UTC, inz- commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
thanks for pointing out the obvious :)

2020-05-29 08:16 UTC, inz- commented
This should have been obvious, but thanks ;)
Has been changed

2020-05-30 18:30 UTC, Almantask approved these changes
Looks good

2020-05-30 18:30 UTC, closed without merging