Chapter1/homework/5
Almantask/CSharp-From-Zero-To-Hero pull request #403
Opened 2020-05-21 10:38 UTC by mkasarci

First Pull Request hope it's okay.

2020-05-23 13:51 UTC, Almantask requested changes
Be mindful of what you already have and where possible, reuse functions.

2020-05-23 13:51 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            if (array != null)
You can denest it:
if(array == null) return;

2020-05-23 13:51 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +                            temp = array[i];
Can be extracted to swap fucntion

2020-05-23 13:51 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertFirst(int[] array, int number)
Reuse the InsertAt function

2020-05-23 13:51 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertLast(int[] array, int number)
Reuse InsertAt function

2020-05-23 22:22 UTC, mkasarci commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertFirst(int[] array, int number)
Yeah I'm so silly

2020-05-23 22:24 UTC, mkasarci commented
I've refactored my code. Can you check if it is okay?

2020-05-30 13:07 UTC, Almantask approved these changes
Sorry for missing this... No idea how did it slip my eyes for so long

2020-05-30 13:08 UTC, closed without merging