Chapter1/homework/5
Almantask/CSharp-From-Zero-To-Hero pull request #404
Opened 2020-05-21 14:42 UTC by draksa15

2020-05-23 13:52 UTC, Almantask requested changes
Please implement your own function and don't use C# language features yet.

2020-05-23 13:52 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            Array.Sort(array);
Implement your own sort.

2020-05-23 13:52 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            Array.Reverse(array);
Implement your own reverse.

2020-05-23 15:34 UTC, draksa15 commented
Fixed!

2020-05-30 13:08 UTC, Almantask approved these changes
Sorry for forgetting to check back! Looks good now!

2020-05-30 13:08 UTC, closed without merging