Chapter1/homework/5
Almantask/CSharp-From-Zero-To-Hero pull request #411
Opened 2020-05-24 13:57 UTC by Dreniak

2020-05-25 15:49 UTC, jdphenix requested changes

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            }
`int[] newArray = new int[array.Length + 1]` will throw a null reference exception if `array` is null. `InsertAt` is supposed to return a new array with the single new element.

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertAt(int[] array, int number, int index)
If the index is out-of-bounds to the input array, this method should return the array unmodified.

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          }
Consider implementing this method in terms of `InsertAt` - hint: maybe this method could be replaced completely with `InsertAt(0)`

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          }
Consider implementing this method in terms of `InsertAt`

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveAt(int[] array, int index)
This method should be returning the original array unmodified if the index is out of range. Consider handling that at the beginning of the method.

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          }
Consider implementing this is terms of `RemoveAt`

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          }
Consider implementing this is terms of `RemoveAt`

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            if (array.Length == 0 || array == null)
Flip this around. `array.Length` will throw a NullReferenceException. Remember that `||` is short-circuiting.

2020-05-25 15:49 UTC, jdphenix commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +        }
Can delete this if it's not used.

2020-05-27 01:00 UTC, Dreniak commented
I'm having some trouble performing tests because of my Visual Studio. Hopefully by tomorrow i'll have it sorted and will be able to fix the remaining errors.

2020-05-27 02:07 UTC, jdphenix requested changes
Several tests are failing, 

- InsertAt_Returns_Array_WithExpectedElements
- InsertLast_Returns_Array_With_ExpectedElements
- RemoveLast_Returns_Array_With_ExpectedElements

These will need to be be passing.

2020-05-27 02:07 UTC, jdphenix commented
> 
> 
> I'm having some trouble performing tests because of my Visual Studio. Hopefully by tomorrow i'll have it sorted and will be able to fix the remaining errors.

Okay, that sounds good. Just confirm when you'd like another review.

2020-05-28 00:30 UTC, Dreniak commented
Ok, I sorted things out. Worked on the code for some time today. Fixed the error I noticed that was related to RemoveAt and InsertAt usage of index. I tested every situations I could imagine and still don't know where these errors are coming from. I cannot see the array they used for input to debug so I'm quite lost.

2020-05-28 01:27 UTC, jdphenix commented
> 
> 
> Ok, I sorted things out. Worked on the code for some time today. Fixed the error I noticed that was related to RemoveAt and InsertAt usage of index. I tested every situations I could imagine and still don't know where these errors are coming from. I cannot see the array they used for input to debug so I'm quite lost.

I would consider reviewing the [Lesson 6 material](https://discordapp.com/channels/475671343463923714/665673287778697248/672174368973127722). I'm also usually on the Discord as @jdphenix if you'd like to poke me in one of the question channels. 

For your still failing tests, I would look at the following cases: 

- What happens when the array is null? Is there a way you might be able to consistently apply null handling behavior in every method?
- For InsertAt, what happens when you try to insert an element outside of the bounds of the array using your methods?

2020-05-28 16:29 UTC, Dreniak commented
Finally finished it. I did a lot of newbie's mistakes on the things i had understood, although I was unable to get how I really was supposed to handle empty arrays in InsertAt method, which I only figured out after checking some other Pull Request. I don't think the instructions were clear in this one.
Glad I finished it, really made me improve as a developer.

2020-05-28 20:29 UTC, Almantask approved these changes
Looks good, just try to instead of writing a comment, doing the same but by expressing yourself in code.

2020-05-28 20:29 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            else if (index < 0 || index > array.Length) //If index is OutOfBounds
instead of a comment, make code speaking for itself:
```
bool outOfBounds = index < 0 || index > array.Length;
..
else if(outOfBounds)
{
  return array;
}
```
no comment is needed!
Try looking at the example I made some time ago regarding code speaking for itself.
Code with many comments:
https://github.com/Realm-of-Everlasting-Code/C-Sharp/blob/master/General/CodeSmells/Comments/Src/Comments.Problem/Algorithm%20Without%20Explanation/Better/Sorting.cs
Code that speaks for itself:
https://github.com/Realm-of-Everlasting-Code/C-Sharp/blob/master/General/CodeSmells/Comments/Src/Comments.Problem/Algorithm%20Without%20Explanation/Good/Sorting.cs

2020-05-28 20:29 UTC, closed without merging