Chapter 1 Homework 3
Almantask/CSharp-From-Zero-To-Hero pull request #413
Opened 2020-05-24 20:05 UTC by Sqelson

Tests appear to pass and program works as I intended and should fulfil the criteria, found grasping the syntax and where to put things quite difficult at first and a surprising step up from the previous homework but looking at examples of functions and classes online helped a lot.

2020-05-25 19:04 UTC, jdphenix requested changes
I'm pleased with this, just a couple of minor tweaks. You shouldn't have to change the Tests project.

2020-05-25 19:04 UTC, jdphenix commented on Tests/BootCamp.Chapter.Tests/Lesson3Tests.cs
> -            var bmi = Checks.CalculateBmi(weightKg, heightM);
You should leave the test class alone for now. Just make sure the method is called CalculateBmi (note the capitalization).

2020-05-25 19:04 UTC, jdphenix commented on Src/BootCamp.Chapter/Lesson3.cs
> +            return float.Parse(Console.ReadLine());
Consider `float.Parse(string, IFormatProvider)` - you can pass in `CultureInfo.InvariantCulture` here.

2020-05-25 19:04 UTC, jdphenix commented on Src/BootCamp.Chapter/Checks.cs
> +        public static double CalculateBMI(float weight, float height)
Keep this returning `float`

2020-05-25 22:30 UTC, Sqelson commented on Tests/BootCamp.Chapter.Tests/Lesson3Tests.cs
> -            var bmi = Checks.CalculateBmi(weightKg, heightM);
Ok, I will leave the tests alone in the future until explicitly told to edit them.

2020-05-25 22:30 UTC, Sqelson commented on Src/BootCamp.Chapter/Lesson3.cs
> +            return float.Parse(Console.ReadLine());
Took some time but figured out why this was required, and noticed it was on the wiki to implement it, thanks for the tip!

2020-05-25 22:30 UTC, Sqelson commented on Src/BootCamp.Chapter/Checks.cs
> +        public static double CalculateBMI(float weight, float height)
Changed it back to float.

2020-05-25 22:31 UTC, Sqelson commented
Thanks for the feedback, I have implemented the changes recommended, and also added a few comments as I realised I hadn't put any in yet.

2020-05-26 02:07 UTC, jdphenix approved these changes
Excellent work, thanks!

2020-05-26 16:27 UTC, closed without merging