Chapter1 homework 9
Almantask/CSharp-From-Zero-To-Hero pull request #415
Opened 2020-05-25 12:21 UTC by mkasarci

2020-05-25 19:30 UTC, jdphenix requested changes
Looks pretty good, just a couple of nitpicks.

2020-05-25 19:30 UTC, jdphenix commented on Src/BootCamp.Chapter/BinaryConverter.cs
> +            string binaryValue = "";
Consider using a `StringBuilder` and returning `StringBuilder.ToString()` at the end.

2020-05-25 19:30 UTC, jdphenix commented on Src/BootCamp.Chapter/BinaryConverter.cs
> +            //return Convert.ToString(Convert.ToInt32(number, 16), 2);
Remove unnecessary comment.

2020-05-25 19:30 UTC, jdphenix commented on Src/BootCamp.Chapter/ArrowMovement.cs
> +            return 'a';
Looks pretty good. Don't forget the default case should return ↥.

2020-05-26 07:56 UTC, mkasarci commented
I've changed the code and use StringBuilder. Can you please check again?

2020-05-26 12:34 UTC, jdphenix approved these changes
Good work, thank you!

2020-05-26 16:27 UTC, closed without merging