Chapter2/homework/2
Almantask/CSharp-From-Zero-To-Hero pull request #418
Opened 2020-05-26 16:41 UTC by mkasarci

2020-05-27 01:13 UTC, jdphenix requested changes
My review touches on required elements. 

You are welcome to continue to submit changes to the optional inventory implementation and I'll be happy to review further.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Shop.cs
>          }
This constructor seems superfluous - I don't see where it's invoked.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Shop.cs
> +        }
I think this may be a part of an implementation in progress. I don't see where this is invoked.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Inventory.cs
> +                if (item == indexItem)
```suggestion
            foreach (Item candidate in _items)
            {
                if (item == candidate)
```

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Inventory.cs
> +            array = temp;
I believe these lines can be removed.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Inventory.cs
> +            Object[] temp = new object[array.Length - 1];
Consistency is nice - use `object` or `Object` throughout your program.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Inventory.cs
> +            if (array == null || index == null) return;
`index` can't ever be null. This conditional can be simplified.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Inventory.cs
> +        private void DeleteIndexShiftElements(Object[] array, int index)
Change to use `Item[]`. In more complex scenarios mismatched array types can result in confusing run-time errors.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Inventory.cs
> +            if ((array.Length - index + 1) < 0) throw new InvalidOperationException("Wrong index or array!");
I feel this check may be unnecessary. You strictly control the arguments passed to DeleteIndexShiftElements - the array is private and index is always controlled by looping through the same.

2020-05-27 01:13 UTC, jdphenix commented on Src/BootCamp.Chapter/Inventory.cs
>          }
Consider an implementation using `Array.Resize()`. 

As an example, `Array.Resize(ref _items, _items.Length + 1)` copies elements to a new array and resizes it to `_items.Length + 1` for you.

2020-05-27 06:41 UTC, mkasarci commented
Wow thanks a lot for the detailed review it is so helpfull. I will look into that.

2020-05-28 01:16 UTC, jdphenix approved these changes
Good job, thank you!

2020-05-28 01:48 UTC, closed without merging