Chapter1/homework/10
Almantask/CSharp-From-Zero-To-Hero pull request #426
Opened 2020-05-28 18:55 UTC by inz-

2020-05-28 19:33 UTC, Almantask requested changes

2020-05-28 19:33 UTC, Almantask commented on Src/BootCamp.Chapter/CaesarCipher.cs
> +            if (message == null)
or empty

2020-05-28 19:33 UTC, Almantask commented on Src/BootCamp.Chapter/CaesarCipher.cs
>          public static string Decrypt(string message, byte shift)
Please redo the decrypt method: what's the difference between encrypt and decrypt 😄 ?

2020-05-29 08:38 UTC, inz- commented
Once again, missed the obvious.. Refactored

2020-05-30 18:31 UTC, Almantask approved these changes
Perfect :)

2020-05-30 18:32 UTC, closed without merging