Chapter3/homework/6
Almantask/CSharp-From-Zero-To-Hero pull request #436
Opened 2020-06-02 13:12 UTC by mkasarci

2020-06-07 04:08 UTC, jdphenix requested changes
Good evening, 
This is pretty good so far! I've got a couple of specific comments I've noted, and one comment about the design of the demo that will need to be addressed. 

It is expected the demo is implemented using handling the specified events, 

a) DemoStarted
b) Example selected (from 2) a, b, c)
c) DemoEnded
d) Application closed

I would start with creating a `Demo` class with event handlers you can subscribe to, like `Started`, `SelectionMade`, etc, so they could be used like `demo.Started += Demo_Started;`

2020-06-07 04:08 UTC, jdphenix commented on Src/BootCamp.Chapter/ContactsCenter.cs
> +            Person person = new Person(personInfo[0], personInfo[1], formatAndParseDateTime(personInfo[2]), personInfo[3], personInfo[4], personInfo[5], personInfo[6]);
Consider eliminating the magic numbers for column order here. Naming constants instead is much more readable, e.g. 

    const int FirstNameField = 0;
    // later
    Person person = new Person(
        personInfo[FirstNameField],
        personInfo[SurnameField], ...

2020-06-07 04:08 UTC, jdphenix commented on Src/BootCamp.Chapter/ContactsCenter.cs
> +                bool firstIndexFlag = true;
Unneeded, remove.

2020-06-10 13:20 UTC, mkasarci commented on Src/BootCamp.Chapter/ContactsCenter.cs
> +                bool firstIndexFlag = true;
I got exception when I deleted this. Because first line of the .csv file is contain header. I've just skip the first line which contains header when I check streamReader.ReadLine() is empty. And I start my while loop at 2nd line of he .csv file with that code. I couldn't workaround this issue without these codes. Do you have any advice?

2020-06-14 11:24 UTC, Almantask requested changes

2020-06-14 11:24 UTC, Almantask commented on Src/BootCamp.Chapter/Program.cs
> +                Demo.Demo_Started?.Invoke(Selection(), EventArgs.Empty);
The whole point of events is that the implementation for handler comes from outside. The Demo.Started delegate should be a delegate outside of demo itself. Else, you could just call Demo.Started, right?

`Demo_Started` is good, if you had the right name for it `DemoStarted` is a better name.

2020-06-14 11:24 UTC, Almantask commented on Src/BootCamp.Chapter/Program.cs
> +                Demo.Demo_Started?.Invoke(Selection(), EventArgs.Empty);
Your demo started, should actually call the selection in that case. right now, you manually invoke an extra method on top of event. Be more organic:
`Demo.DemoStarted += Selection;`

2020-07-01 16:19 UTC, Almantask commented
EXpired

2020-07-01 16:19 UTC, closed without merging