Chapter1/homework/5
Almantask/CSharp-From-Zero-To-Hero pull request #474
Opened 2020-07-08 03:00 UTC by daman92

I tried the null check two different ways with no success. Any guidance appreciated. Other wise, all tests complete.

2020-07-08 22:32 UTC, daman92 commented
In the project all tests now pass. Not sure why Codacy and Azure pipelines keeps failing. Thanks for the tip on the null check.

2020-07-11 09:29 UTC, Almantask requested changes

2020-07-11 09:29 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
Reuse RemoveAt

2020-07-11 09:29 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveFirst(int[] array)
Reuse RemoveAt

2020-07-11 09:29 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertFirst(int[] array, int number)
Reuse insertAt

2020-07-11 09:29 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertLast(int[] array, int number)
Reuse insertAt

2020-07-12 03:16 UTC, daman92 commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
implemented

2020-07-12 03:16 UTC, daman92 commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveFirst(int[] array)
implemented

2020-07-12 03:16 UTC, daman92 commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertFirst(int[] array, int number)
implemented

2020-07-12 03:16 UTC, daman92 commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertLast(int[] array, int number)
implemented

2020-07-13 21:40 UTC, Almantask approved these changes
Well done

2020-07-13 21:40 UTC, closed without merging