Chapter1/Homework 5
Almantask/CSharp-From-Zero-To-Hero pull request #510
Opened 2020-07-27 10:52 UTC by Tailor-AI

First draft for homework 5.

2020-07-28 18:54 UTC, Almantask requested changes
Reuse code more 🛩️

2020-07-28 18:54 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
Reuse RemoveAt

2020-07-28 18:54 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveFirst(int[] array)
Reuse RemoveAt

2020-07-28 18:54 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertFirst(int[] array, int number)
Reuse InsertFirst

2020-07-28 18:54 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertLast(int[] array, int number)
Reuse InsertFirst

2020-07-29 08:07 UTC, Tailor-AI commented
Reused RemoveAt and InsertAt in this second draft.

2020-07-29 08:10 UTC, Tailor-AI commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
ok, fixed

2020-08-04 16:27 UTC, Almantask approved these changes
Yes, that's exactly what I was expecting 😄

2020-08-04 16:27 UTC, closed without merging