Implement functionality for Chapter 1, Homework 5
Almantask/CSharp-From-Zero-To-Hero pull request #552
Opened 2020-09-11 13:31 UTC by kungfuphil

Add functionality to ArrayOperations methods.

2020-09-15 15:45 UTC, Almantask requested changes

2020-09-15 15:45 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            Array.Sort(array);
Please implement those manually.

2020-09-15 15:45 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +            Array.Reverse(array);
Please implement those manually.

2020-09-15 15:45 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
Reuse removeAt

2020-09-15 15:45 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveFirst(int[] array)
Reuse removeAt

2020-09-15 15:45 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertFirst(int[] array, int number)
Reuse InsertAt

2020-09-15 15:45 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertLast(int[] array, int number)
Reuse InsertAt

2020-09-15 18:46 UTC, kungfuphil commented
Can't believe I didn't think of reusing those methods! I've made all the recommended changes.

2020-09-16 19:51 UTC, Almantask approved these changes
Looks good 😄

2020-09-16 19:51 UTC, closed without merging