Chapter1/homework/5
Almantask/CSharp-From-Zero-To-Hero pull request #562
Opened 2020-09-18 21:13 UTC by Nothing-Too-Fancy

You have contradicting test cases for InsertAt_Returns_Array_WithExpectedElements.

Case 2, 3, and 4 have an empty input array. In Case 2 and 4, the expected output is an empty array. In Case 3, the expected output is an array of size 1.

2020-09-18 21:57 UTC, Almantask commented
> You have contradicting test cases for InsertAt_Returns_Array_WithExpectedElements.
> 
> Case 2, 3, and 4 have an empty input array. In Case 2 and 4, the expected output is an empty array. In Case 3, the expected output is an array of size 1.

No, only case 1 and 2 (when array is out of bounds, we return the same array).
Could you elaborate more?
here are the test cases:
```cs
            // Index out of bounds- returns original array.
            yield return new object[] { Arrays.Empty, 1, Arrays.Empty };
            yield return new object[] { Arrays.Empty, -1, Arrays.Empty };

            // Null or empty- create a new array with that element.
            yield return new object[] { Arrays.Empty, 0, new[] { ElementToBeInserted } };
            yield return new object[] { Arrays.Null, 0, new[] { ElementToBeInserted } };
            
            yield return new object[] { Arrays.TwoElementsDesc, 1, new[] { 1, ElementToBeInserted, 0 } };
```

2020-09-18 22:10 UTC, Nothing-Too-Fancy commented
Ah ok you are right. My brain didn't process that index 1 was out of bounds. What is confusing to me still is that it seems an out of bounds index takes precedent over a null or empty array, in terms of which "error" value should be returned. Is that right? 

The <returns> portion of the function "docs" states:
<returns>A new array with element inserted at a given index. **If an array is empty or null, returns new array with number in it.**</returns>

In order to get the tests to pass, it seems you have to first do a null check, then an index bounds check, and finally the empty array check. Am I on the right track there?

2020-09-19 09:51 UTC, Almantask commented
Actually, when it is null, it does nothing - just returns the same array

2020-09-19 18:27 UTC, Nothing-Too-Fancy commented
According to the instructions it should return a new array with the desired number and also this test case:
yield return new object[] { Arrays.Null, 0, new[] { ElementToBeInserted } };

2020-09-19 18:39 UTC, Almantask commented
> According to the instructions it should return a new array with the desired number and also this test case:
> yield return new object[] { Arrays.Null, 0, new[] { ElementToBeInserted } };

Yes, that's the requirements. I mean it might sound silly, but it's a requirement 😄

2020-09-19 18:48 UTC, Nothing-Too-Fancy commented
But what I am saying is that an empty array falls under the same requirements as stated in the function docs, yet the test cases do not reflect that. Maybe I'm not explaining correctly or I am confused...

2020-09-19 18:52 UTC, Nothing-Too-Fancy commented
I will modify the code, but I'm just saying the instructions do not state anything about how out of bounds indexes are handled.

2020-09-21 16:59 UTC, Almantask commented
> I will modify the code, but I'm just saying the instructions do not state anything about how out of bounds indexes are handled.

I can miss things 

> But what I am saying is that an empty array falls under the same requirements as stated in the function docs, yet the test cases do not reflect that. Maybe I'm not explaining correctly or I am confused...

The requirements might be poorly worded compared to tests. Tests is #1 source of truth.

2020-09-21 17:01 UTC, Almantask requested changes

2020-09-21 17:01 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
> +                    Array.Sort(array);
Write a custom implementation of this.

2020-09-21 17:01 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static void Reverse(int[] array)
Custom implmentation.

2020-09-21 17:01 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveLast(int[] array)
Reuse removeAt

2020-09-21 17:01 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] RemoveFirst(int[] array)
Reuse removeAt

2020-09-21 17:01 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertFirst(int[] array, int number)
Reuse InsertAt

2020-09-21 17:01 UTC, Almantask commented on Src/BootCamp.Chapter1/ArrayOperations.cs
>          public static int[] InsertLast(int[] array, int number)
Reuse InsertAt

2020-09-21 17:25 UTC, Nothing-Too-Fancy commented
I hope you know I am not trying to criticize, only to understand. I will use the tests themselves as the source of truth from now on.

2020-09-21 17:27 UTC, Almantask commented
> I hope you know I am not trying to criticize, only to understand. I will use the tests themselves as the source of truth from now on.

Please do say criticism, that is good, but mentioning it once is enough. I understand that things are imperfect and I am on my best effort of refining it.

Actually, I have paused the lessons a week ago and have been going through all the lessons from day 1 and updating the material, double-checking tests, adding wikis if there weren't any.

Criticism leads to perfection. Please don't stop that.

2020-09-21 17:29 UTC, Nothing-Too-Fancy commented
Will do. Appreciate the work you've done here.

2020-09-29 20:08 UTC, closed without merging