Chapter 1, Lesson 4 homework.
Almantask/CSharp-From-Zero-To-Hero pull request #563
Opened 2020-09-19 11:19 UTC by vytcka

Checker in VS doesn't work, so I'll check it by using PR.

2020-09-19 15:44 UTC, vytcka commented
I have no clue honestly what to do right now, probably will watch Lesson 5 and then try to comeback because I'm stuck on this for long time already and Float checks don't show if they're correct or wrong.

2020-09-19 16:07 UTC, vytcka commented
Done all checks, I think it should be alright now.

2020-09-21 17:04 UTC, Almantask requested changes
A bit overly complex validation

2020-09-21 17:04 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson4.cs
> +            {
The body of for loop could be moved into a function. That would leave you with two options then:
A- just call the same function twice
B- do what you do, but in a body call a function instead.

2020-09-21 17:04 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson4.cs
> +            if (height <= 0)
Can be simplified:
```cs
string error = "";
if(weight <= 0)
{
 error = ...;
}
else if(height <= 0)
{
  error += "";
}
if(string.IsNullOrEmpty(error))
{
  print(error);
  return -1;
}
else
{
  return bmi;
}
```

2020-09-24 11:54 UTC, vytcka commented
Okay, so I redid it a bit. Now I added another function AskingInformation and called it in Demo function. 
Then I tried simplifying this thing, but not sure if I got it right. It's pretty hard to understand this, but I hope I can get better at it.

2020-09-25 17:28 UTC, Almantask approved these changes
Looks better 😄

2020-09-25 17:28 UTC, closed without merging