Managed to finished all the tasks as well as pass all the tests Chapter/Homework/3
Almantask/CSharp-From-Zero-To-Hero pull request #567
Opened 2020-09-20 23:07 UTC by Sakariya-Mohumed

2020-09-21 17:10 UTC, Almantask requested changes
Try to name things a bit better:
- variables should be camelCase
- method names should be PascalCase
- methods are actions- they should be named after verbs

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +        public static float BMICalculator(float weightcal, float heightcal)
method names should be verbs not nouns. Change this to `CalculateBmi`

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +        public static float BMiRequests(string prompt)
Rename to verb

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +        public static int ageRequests(string message)
Rename to verb

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +            return stringinput;
Rename to verb

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +            var ageconv = int.Parse(input);
keep it simple and stupid (KISS): age

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +            var bm_1 = float.Parse(bm);
keep it simple and stupid (KISS):
bmi = float.Parse(console.ReadLine());

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +            var stringinput = Console.ReadLine();
keep it simple and stupid (KISS): input

2020-09-21 17:10 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +            var totalbmi = weightcal / heightsquared;
keep it simple and stupid (KISS): bmi

2020-09-21 20:02 UTC, Sakariya-Mohumed commented
I have edited the code and thank you very much for the feedback

2020-09-22 16:13 UTC, Almantask approved these changes

2020-09-22 16:13 UTC, Almantask commented
Looks good 😄

2020-09-22 16:13 UTC, closed without merging