Chapter 1 Homework 3
Almantask/CSharp-From-Zero-To-Hero pull request #568
Opened 2020-09-21 19:33 UTC by EMonfort

Added the code for chapter 1 homework 3

2020-09-22 16:12 UTC, Almantask requested changes

2020-09-22 16:12 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +            Console.WriteLine("Person 1:");
Make this simply 2 function calls.

2020-09-23 00:09 UTC, EMonfort commented on Src/BootCamp.Chapter/Lesson3.cs
> +            Console.WriteLine("Person 1:");
> Make this simply 2 function calls.

Made the requested changes

2020-09-25 17:29 UTC, Almantask approved these changes
Looks good 😄

2020-09-25 17:29 UTC, Almantask commented on Src/BootCamp.Chapter/Lesson3.cs
> +            CallFunctions("Person 1");
Name better.

2020-09-25 17:29 UTC, closed without merging